### PR TITLE
fix: consistent border UI in all component

### LINKED ISSUE #132: Amount of rounded should consistent
All buttons, dialogs, and boxes should have the same corner radius.

NO EXCEPTION AT ALL

### PR DESCRIPTION
**Pull request by phoenixit99**
Fixed #132 
Related #126

### CODE REVIEW

File: apps/web/src/components/add-account-modal/index.tsx [hunk 1]
```diff
@@ -92,13 +86,13 @@ const AddAccountModal: React.FC<AddAccountModalProps> = ({ isOpen, onClose }) =>
           ))}
         </div>
 
-        <div className="modal-input-container">
-          <label className="modal-label" htmlFor="password">
+        <div className="modal-input-container pl-1 pr-1">
+          {/* <label className="modal-label" htmlFor="password">
```
Comment (b00f) [inline apps/web/src/components/add-account-modal/index.tsx:90]: Do we need to keep this commented code?

File: apps/web/src/components/add-account-modal/index.tsx [hunk 2]
```diff
@@ -92,13 +86,13 @@ const AddAccountModal: React.FC<AddAccountModalProps> = ({ isOpen, onClose }) =>
...
             Password
-          </label>
+          </label> */}
 
-          <div className="input-MasterPassword">
-            <input
+          {/* <div className="input-MasterPassword"> */}
```
Comment (b00f) [inline apps/web/src/components/add-account-modal/index.tsx:94]: Same here?

**Review by b00f — CHANGES_REQUESTED** [review]
Can we have command like `yarn fmt` to format all code?

**Review by b00f — APPROVED** [review]
