### PR TITLE
fix(web): remove validate password on send form and password modal

### LINKED ISSUE #164: Issue with Special Character Definition
We have encountered an issue regarding the definition of special characters: [GitHub Issue #44.](https://github.com/pactus-project/pactus-wallet/issues/44)

Currently, users who signed up during Phase 1 are already registered. Please see the example below:

Image. 

We need to provide support for these existing users, ensuring compatibility with the new special character rule.

Allowed characters:  ~!@#$%^&*()_-+=

### PR DESCRIPTION
**Pull request by quocthinhred**
## Description

remove validate password on send form and password modal

## Related Issue

Fixes #164

### CODE REVIEW

File: apps/web/src/components/password-modal/index.tsx [hunk 1]
```diff
@@ -111,14 +99,12 @@ const ShowPrivateKeyModal: React.FC<ShowPrivateKeyModalProps> = ({ isOpen, onClo
...
-            onFocus={handlePasswordFocus}
-            onBlur={handlePasswordBlur}
           />
-          <PasswordStrengthIndicator
+          {/* <PasswordStrengthIndicator
             password={password}
             className="mt-2"
             isFocused={isPasswordFocused}
-          />
+          /> */}
```
Comment (phoenixit99) [inline apps/web/src/components/password-modal/index.tsx:107]: Please remove unuse code

File: apps/web/src/components/send/SendForm.tsx [hunk 2]
```diff
@@ -146,16 +143,16 @@ const SendForm: React.FC<SendFormProps> = ({
...
-    } else {
-      setPasswordError('');
-    }
-  };
+  //   if (newPassword && !validatePassword(newPassword)) {
+  //     setPasswordError(t('passwordRequirements'));
+  //   } else {
+  //     setPasswordError('');
+  //   }
+  // };
```
Comment (phoenixit99) [inline apps/web/src/components/send/SendForm.tsx:155]: Remove unuse code too

**Review by phoenixit99 — APPROVED** [review]
