### PR TITLE
fix: fix ui get start page (use tailwindcss)

### LINKED ISSUE #136: [BUG]: The UI issue in get-start page
Image

1. Issues:
No padding (right  or left)
No horizontal scrollbar

Image

2. Issues:
Suddenly padded (inconsistent)
No horizontal scrollbar

3. Issues:
Fonts size change inconsistently. Should have the same ratio. 
Items look centred, and should be left aligned. 

4. Issues:
Header font changes 

5. Note that “Welcome to” is smaller and a  little bit pale.

Important Note:  Position of “Let’s start” button should not changes by changing the size of screen

### PR DESCRIPTION
**Pull request by quocthinhred**
## Description

fix ui get start page (use tailwindcss)

## Related Issue

Fixes #136

### CODE REVIEW

File: apps/web/src/scenes/get-started/components/welcome/index.tsx [hunk 1]
```diff
@@ -47,57 +47,57 @@ const Welcome = () => {
...
             checked={isChecked}
             onChange={handleCheckboxToggle}
             aria-labelledby="terms-text"
           />
-          <label id="terms-text" htmlFor="terms-checkbox" className="welcome__terms-text">
+          <label id="terms-text" htmlFor="terms-checkbox" className="text-text-secondary text-xs font-regular leading-normal cursor-pointer select-none">
             {t('iHaveReadAndAgreed')}{' '}
-            <span className="welcome__terms-highlight">{t('termsAndConditions')}</span>.
+            <span className="bg-gradient-primary bg-clip-text text-transparent [-webkit-background-clip:text] [-webkit-text-fill-color:transparent] [text-wrap:nowrap]">{t('termsAndConditions')}</span>.
           </label>
```
Comment (phoenixit99) [inline apps/web/src/scenes/get-started/components/welcome/index.tsx:97]: Please use the checkbox component for reuse . check here https://github.com/pactus-project/pactus-wallet/blob/c9a4cd8034023cbc52bbe10840e1d4e8b0b2f527/apps/web/src/stories/Checkbox.stories.tsx#L2

File: apps/web/src/scenes/get-started/components/welcome/index.tsx [hunk 2]
```diff
@@ -47,57 +47,57 @@ const Welcome = () => {
...
         </div>
         <button
-          className="btn btn-primary welcome__cta-button"
+          className="btn btn-primary tablet:w-auto tablet:max-w-[600px] mt-xs h-button-desktop w-full max-w-full"
           onClick={() => navigate('/get-started?step=add-wallet')}
           disabled={!isChecked}
           aria-disabled={!isChecked}
```
Comment (phoenixit99) [inline apps/web/src/scenes/get-started/components/welcome/index.tsx:103]: use button component at here https://github.com/pactus-project/pactus-wallet/blob/c9a4cd8034023cbc52bbe10840e1d4e8b0b2f527/apps/web/src/stories/Button.stories.tsx#L5

File: apps/web/src/scenes/get-started/components/welcome/index.tsx [hunk 3]
```diff
@@ -47,57 +47,57 @@ const Welcome = () => {
...
+                className="w-[32px] h-[32px] shrink-0"
                 aria-hidden="true"
                 width={32}
                 height={32}
               />
-              <div className="welcome__feature-content">
-                <h3 className="welcome__feature-title">{feature.title}</h3>
-                <p className="welcome__feature-description">{feature.description}</p>
+              <div className="flex flex-col gap-xs">
+                <h3 className="text-text-primary tablet:!text-xl font-medium !leading-tight text-lg">{feature.title}</h3>
```
Comment (phoenixit99) [inline apps/web/src/scenes/get-started/components/welcome/index.tsx:71]: The title and description are used in many places. Please help me create the component for these. We can reduce the duplicate code

**Review by phoenixit99 — APPROVED** [review]
